### ISSUE TITLE
Bluetooth keyboard not in /dev/input/by-path/ or by-id

### ISSUE THREAD

**Issue by JustSaX** [jbensmann/mouseless#10]
I have a bluetooth keyboard that does not show up in  /dev/input/by-path/ or by-id at least not with `kbd` in the name.

Is it possible to connect a Bluetooth keyboard with mouseless?

Thanks for your help!

**Comment by jbensmann** [comment]
Yes that should be possible, but I am not sure if every keyboard shows up in one of the two directories and has `kbd` in it, so if there are other ones that sound plausible you might try them.

Otherwise one can also always use the device `/dev/input/eventXY` (here XY is a number), you could use `libinput list-devices` to find out which is the right one, or run `journalctl -f` and then plug in the keyboard. But this device can change when the keyboard gets replugged.

**Comment by JustSaX** [comment]
With `cat /proc/bus/input/devices` I can get the event number and put that into the config.yaml. This works but as you wrote the event number might change after reboot.

Are there no other options? Manually updating the config.yaml is quite tedious.

**Comment by jbensmann** [comment]
Yes one could update the config file automatically before starting mouseless with something list this:
```
#!/usr/bin/env sh
device=$(libinput list-devices | grep -i 'KEYBOARD_NAME' -A10 | grep 'Capabilities.*keyboard *$' -C 5 | grep "Kernel:" | sed 's_.*\(/dev/input/event[0-9]*\).*_\1_')
[ -z "$device" ] && echo "device not found" && exit 1
echo "device found: $device"
sed -i 's_- "/dev/input/event[0-9]*"_- "'"$device"'"_' ~/.config/mouseless/config.yaml
mouseless --config ~/.config/mouseless/config.yaml
```
Here you have to replace KEYBOARD_NAME with the name of your keyboard as it is shown in `libinput list-devices`, and if it finds the device, it replaces it in the config file, where a device with name `/dev/input/eventXY` has to be present. This is a little hacky but I currently do know a better option.
