### ISSUE TITLE
Mouse acceleration

### ISSUE THREAD

**Issue by vilcans** [jbensmann/mouseless#18]
The mouse cursor currently moves at a constant speed. The speed may be too slow for moving the cursor longer distances, and too fast to get the precision you need. It's possible to modify the speed if you bind the `speed` function to a modifier key, but that is not always so convenient to use.

I propose modifying the cursor's speed over time, so it accelerates in the direction you are pressing (a bit like Super Mario and other user-controlled objects in games).

I have a working implementation of this [in a branch](https://github.com/vilcans/mouseless/tree/mouse-acceleration).
I'm going to play around with it for a while to feel if it can be improved. I'm considering retardation as well, so the cursor doesn't stop immediately when you release the key.

**Comment by jbensmann** [comment]
Thanks for the contribution and sorry for the late response.

There is no mouse acceleration yet because I think speed modifiers are by far the fastest way to get to a specific location since one does not have to wait for the mouse to accelerate. But I am sure many people would prefer it, and as you said it might be more convenient to use in some situations.

I have only some suggestions:
- instead of specifying the acceleration, it might be more intuitive to specify the time it takes to accelerate to full speed, and call the field `mouseAccelerationTime` (for the unit I would choose ms because other time intervals are given in ms as well)
- I would rename `mouseStartSpeed` to `startMouseSpeed`, but only to be consistent with `baseMouseSpeed`
- in the example config I would like to disable acceleration by default by setting `mouseAccelerationTime` to 0, or maybe use a low value like 500 ms

What do you think?

And I have one other question: in your example config, you set `mouseStartSpeed` to 1.5, does such a low value make any difference to 0?

**Comment by vilcans** [comment]
Sounds good to me. I'll do these changes. Regarding mouseStartSpeed being 1.5 in the example, that was wrong because there was a bug where mouseStartSpeed was in units per 20 ms tick instead of per second. That should actually be 75.

**Comment by jbensmann** [comment]
Ah ok 75 makes more sense. Thank you!

**Comment by vilcans** [comment]
I made the changes you suggested in my branch. But I've started thinking about the deceleration. That is still the amount of deceleration in units per second squared. To be consistent that should also be a time in milliseconds. Then it could be how long it should take to stop from the maximum speed.

The way I actually would like to try out with deceleration it is to make the cursor stop in a given time, or following an exponential curve, so it doesn't take that much longer to stop from a higher speed than from a lower one.

**Comment by jbensmann** [comment]
Thanks, yeah I assumed it would be obvious to do the same with deceleration, but of course I should have mentioned it :)
Maybe an exponential curve would also make sense for acceleration, because then one has more time when the mouse moves slower but still gets to the final speed in short time.

One might also take some inspiration from this side: https://github.com/qmk/qmk_firmware/blob/master/docs/feature_mouse_keys.md
It is from QMK, a firmware for keyboards that also allows movement of the mouse, similar to mouseless. They have different modes that defines among other things how the cursor accelerates (e.g. linear or quadratic), maybe we could also add a field (like `mouseAccelerationMode`) that defines in which curve the mouse accelerates and decelerates. 

But I am not sure what curves make sense and if one needs different ones for acceleration and deceleration, I might also play around with it a little on the weekend, that's probably the best way to find out.

**Comment by jbensmann** [comment]
So I have tested a little, but I am still not sure what the best option is. Maybe we could simply start with linear acceleration and deceleration, and add more options later.

And in the current implementation the time it takes to decelerate should be the same whether one presses a speed modifier or not, right? Because the speedFactor simply gets multiplied on top of the speed in the last step. The only case where it would take longer is when using move with values greater than 1, e.g. `move 2 0`, but this is probably rarely used, so this might be acceptable.

**Comment by vilcans** [comment]
That QMK page led me to an interesting Wikipedia article about [Mouse keys](https://en.wikipedia.org/wiki/Mouse_keys).

I've implemented exponential acceleration/deceleration (basically the mk_curve setting in that article). I think it's a bit easier to navigate the mouse cursor now, I've found that these settings work well for me:

```
# the default speed for mouse movement
baseMouseSpeed: 1700.0
# speed of the mouse when it starts moving
startMouseSpeed: 50.0
# The shape of the mouse's acceleration curve
mouseAccelerationCurve: 2.0
# how many milliseconds for the mouse to accelerate up to baseMouseSpeed; 0 to reach top speed immediately
mouseAccelerationTime: 1000.0
# The shape of the mouse's deceleration curve
mouseDecelerationCurve: 3.0
# how quickly the mouse slows down, or 0 to stop immediately
mouseDecelerationTime: 500.0
```

I had to remove the special handling of diagonal movement because of the way the code works right now. So that has to be cleaned up and fixed.

**Comment by jbensmann** [comment]
Thanks, that's a good idea, I also came across that page but did not think about using that approach. I like it since one can specify many different curves that way.
But I would like to tackle the problem with diagonal movement because the cursor accelerates considerably when moving in 2 directions, I will have to dig a little deeper on the cause, or maybe add a simple fix first that is only approximate.
If you want I can already merge your pull request into a separate branch, and later merge into master when I have found a solution for that.

**Comment by vilcans** [comment]
I just realized that compensating for the diagonal movement can be done simply by multiplying speedFactor with the magic number. I'll try that.

BTW, the magic number is set to 0.546; where did that come from? Because of the Pythagorean theorem, I thought it would be `1/sqrt(2)`  ≈ 0.707.

**Comment by jbensmann** [comment]
Suppose you move right with speed 1 for some time, and then additionally move up with speed 1, what one would expect then is an overall speed of sqrt(2) in the top-right direction, however the speed increases more than that, so that the speed to the right increases as well and is more than 1 now.

I did some research, and it probably has to do with the fact that the speed of the mouse pointer is not linear to the speed of a physical mouse, e.g. when you double the speed of a physical mouse, the speed of the mouse pointer is more than twice as much. At least this is the case for very low or high speeds, one can see in the first graph on this page how it looks like:
https://wayland.freedesktop.org/libinput/doc/latest/pointer-acceleration.html#ptraccel-linear

The yellow one is the default. I tested this at a low speed when identifying the factor 0.546, so this would not be the correct factor for higher speeds. The curve can be changed to be constant (the purple line), but how this is done depends on whether one uses Xorg or Wayland (see e.g. here on how: https://wiki.archlinux.org/title/Mouse_acceleration). But I would rather not add code that depends on that.

So currently I don't see a way we can fix it easily, and I think it would be best to simply remove the fix with the speedFactor for now. It is probably also not a big issue for most people that the pointer accelerates a little more when moving diagonally.

**Comment by vilcans** [comment]
Oh, I see, so libinput treats mouseless as a physical mouse, and applies additional speed based on the speed of the mouse, so it's faster when we move diagonally. It can be disabled in the mouse settings, but that wouldn't be very nice when you want to use a physical mouse from time to time. Maybe mouseless can disable it automatically when it's running?

With acceleration enabled, I think it works well as is. I've been using it with my settings and I'm pretty happy with the speed and precision. But without acceleration I agree that the mouse speed increases in a way I don't expect.

BTW, scaling the speed depending on the input speed like libinput does is what's traditionally called acceleration. Maybe it's confusing that my implementation uses the word acceleration for something that's not exactly the same.

**Comment by jbensmann** [comment]
Yeah I was also confused first what they call acceleration, but I think in our context one can guess what is meant by this and I also would not know a better alternative.

For me it also works fine, I use an accelerationTime of 100 to 150, so that I do not loose much time for acceleration, but can move more precisely than before without having to use a speed modifier.

So if you want I can merge it, and we can later look into the issue with the diagonal movement, maybe there is a way to configure it independent of Xorg and Wayland.

**Comment by vilcans** [comment]
That sounds good. Yes, please merge it. :+1:  Thank you.

**Comment by jbensmann** [comment]
Great, I will then create a separate issue for the diagonal issue.
Thank you for the effort!
