### ISSUE TITLE
Question regarding mouse layer activation

### ISSUE THREAD

**Issue by Shickmo** [jbensmann/mouseless#33]
I am new to mouseless and am using the default config in the readme file. When I am holding down the tab key for example and press the mouse layer keys the mouse moves as expected. 

However, if I hold a, for example, and try to use those same keys the mouse layer never "toggles" on. 

My question is what would the syntax be for me to bind a key, for example "capslock", so when I press that key it turns the mouse layer on and if I press it again "toggles" it off? If there is a another key that is a simpler example then capslock no worries just curious. 

Thanks in advance as holding down tab isn't the easiest with some key presses :)  .

**Comment by jbensmann** [comment]
Hi, in the default config you have to hold a down all the time, if you want to switch to a layer permanently you can use `layer mouse` instead of `toggle-layer mouse`.

If you want to sacrifice e.g. capslock to go to the mouse layer you can use `capslock: layer mouse`. If you also want to exit the mouse layer with capslock, you can define `capslock: layer initial` in the mouse layer.
