### ISSUE TITLE
Pointer moves in fixed directions and with fixed set of speed 

### ISSUE THREAD

**Issue by farazkhancodes** [jbensmann/mouseless#34]
Following are the problems that i have faced using this software:
- the pointer moves in only 8 fixed directions, if i had my target very close to me and somewhere between these 8 possible directions, there's no way for my pointer to reach there without juggling around a few times.
- speed of the pointer is fixed i.e. can only take some discrete values and cannot be changed gradually, no matter how hard i try pressing the "e" key to slow it down as it approaches the target, i fail to press it at the right moment so that i may land exactly on my target, making it a bit finicky to use 

I just love this software and the concept behind it but was facing these issues lately, i wanted it to be a complete replacement to my mouse. I understand that some of the issues cannot be mitigated easily because of how this software is designed, i just wanted to make sure if i am using it right or not. Was this able to replace your mouse in your setup?

I am using the default config [tried changing it as well but didn't help much]

**Comment by jbensmann** [comment]
Hi, I understand the problems you are facing, but I have not found a way to make it work better, there are just some limitations when using a keyboard, since a key has only two states, pressed or not pressed. So you won't get the speed like with a real mouse, but with some practice one can get fast enough to work fluently and hit a target very fast.

I avoid using the mouse pointer where I can (e.g. vim bindings, tiling window manager), in this case mouseless can totally replace a real mouse. Though I use a real mouse from time to time when I have to use a GUI which relies heavily on the mouse pointer.

So I think the most important point to make it work better is practice, and maybe experimenting with different speeds and acceleration times.
