### ISSUE TITLE
Indicator that mouseless is running

### ISSUE THREAD

**Issue by se7en-x230** [jbensmann/mouseless#53]
I thought I create a waybar module that checks if mouseless is running. 
But I as it always runs I could not find a way. 
Any ideas how to create a indicator that mouseless is active?

for now I came up with 
`if ps -e -o pid,tty,stat,cmd | grep -iw "tty1     Sl+  mouseless" | grep -qv grep; then ...
`

which indicates if it is running but not really that it is active.
I don't know how I would get a signal to use that mouseless is not only running but that it is active.

Maybe someone else has a better idea.

I

**Comment by jbensmann** [comment]
You mean you want to know whether mouseless is in the mouse layer, right?

I think there is currently no way to find that out, but I am planning to add an `enterCommand` to the config of a layer that is executed whenever mouseless jumps to that layer, where you could then e.g. create a file or directly update the bar.

But that might take some weeks to come since I am also working on some other features.

**Comment by se7en-x230** [comment]
Yes exactly that is what I was aiming for.

**Comment by se7en-x230** [comment]
Is that topic still worked on or should I close the issue?

**Comment by jbensmann** [comment]
Yes I plan to add it to the next version, but recently did not work as much on mouseless as I would've liked. Hopefully there will be more progress soon.
I will close the issue when the new version has been released.

**Comment by jbensmann** [comment]
One can now define an `enterCommand` and `exitCommand` in each layer.

**Comment by se7en-x230** [comment]
okey got it to work with the full default config.

fd starts mouseless q returns back to mouse BUT I don't get any notification. 
What am I doing wrong?

**Comment by jbensmann** [comment]
Are you running mouseless as root? In this case notify-send does not work correctly, I think because some environment variables are missing.

If you want to use notify-send, the easiest solution would probably be to run mouseless as a non-root user, as described in the README.

You can also run mouseless with the `--debug` flag to see the error message when a command execution fails.

**Comment by se7en-x230** [comment]
okey.

I follow the README: None root systemd service.
binary in ~/.local/bin/ and the mouseless.service in ~/.config/systemd/user/ 
I enable and start the service as a user.
All works fine.

I press fd and I am in mouse mode and q to quit out of it. Looks fantastic, everything works as expected.
Only thing not happening is the notification when I enter and exit mouse mode.

not sure where the --debug infos go 
I added them to the mouseless.service file 
ExecStart=/home/seven/.local/bin/mouseless --debug /home/seven/.config/mouseless/config.yaml

but that does not produce any output
